server {
    listen 9093;
    server_name _;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location = / {
        return 302 /vue-sdb-rec-sign/;
    }

    location /vue-sdb-rec-sign/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /vue-sdb-rec-sign/index.html;
    }
}
